[package]
name = "backend"
version = "0.1.0"
authors = ["Max Taldykin <jorpic@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
failure ="0.1"
log = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tempdir = "0.3"
toml = "0.5"
warp = "0.1"
